### ISSUE TITLE
Unexpected relation created and not removed after disconnecting

### ISSUE THREAD

**Issue by moorscode** [inpsyde/MultilingualPress#273]
When implementing our HREF-Lang implementation some unexpected results occurred on a page which was linked but the link was removed.
`x-default` and language entries are added, but there are no alternatives, so they should not be presented.

It seems that a relation-to-self is being added whenever a relation is created.
This relation-to-self is never removed.

#### Version Information

* PHP: any
* WordPress: 4.8
* MultilingualPress: 2.7

#### Steps to Reproduce

1. Create a relation
1. Remove the relation
1. Check the `multilingual_linked` table for an entry from the source page and blog to itself

#### What I Expected
When no relations exist, no entries to be found in the table.

#### What Happened Instead
An entry always remains after once creating a relation on an object.

**Comment by tfrommen** [comment]
Hey there,

while I understand that the entry is not needed anymore, and it has been fixed for the v3 release already, what exactly is the problem with this? You should not be checking the database (results) directly, but use the API, for example the `mlp_get_linked_elements()` function.

Can you show me (an outline of) what you are doing exactly, so I better understand the **direct** implications?

Thanks,
Thorsten

**Comment by diedexx** [comment]
We noticed that, after removing the link between two posts, the hreflang link of the original post was still present. (When debugging this, we took a look in the database directly.)
We expect that the self-reference is also removed when there are no linked posts remaining, so the hreflang links aren't shown when there aren't any translations (anymore).

**Comment by tfrommen** [comment]
Can you please check if the new branch, [issue/273_orphan_content_relations](https://github.com/inpsyde/MultilingualPress/commit/df4eac96246f72b0d4b7d1254b3f9887ec953574), already works for you?

Thanks.

**Comment by diedexx** [comment]
That works! 👍

**Comment by tfrommen** [comment]
Fixed in df4eac96246f72b0d4b7d1254b3f9887ec953574.
